# Generated by Django 3.1.7 on 2021-03-30 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('folder', '0003_folder_present_in_shared_me_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('privacy', models.BooleanField(default=True)),
                ('trash', models.BooleanField(default=False)),
                ('favourite', models.BooleanField(default=False)),
                ('size', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_file', to='folder.folder')),
                ('present_in_shared_me_of', models.ManyToManyField(related_name='shared_with_me_files', to=settings.AUTH_USER_MODEL)),
                ('shared_among', models.ManyToManyField(related_name='shared_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_modified', 'pk'],
            },
        ),
    ]
