# Generated by Django 3.1.2 on 2021-03-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filesystem_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
