# Generated by Django 3.1.2 on 2021-04-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20210331_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='parent_trash',
            field=models.BooleanField(default=False),
        ),
    ]
