# Generated by Django 3.1.2 on 2021-03-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20210307_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filesystem_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
