# Generated by Django 3.1.2 on 2021-04-02 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_file_parent_trash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='parent_trash',
        ),
    ]
