# Generated by Django 3.1.2 on 2021-03-15 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0004_auto_20210315_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='users',
        ),
        migrations.AddField(
            model_name='file',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
