# Generated by Django 3.1.2 on 2021-04-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_remove_file_parent_trash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
