# Generated by Django 3.1.2 on 2021-03-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_auto_20210315_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='year_in_school',
            field=models.CharField(choices=[('PRIVATE', 'PRIVATE'), ('PUBLIC', 'PUBLIC')], default='PRIVATE', max_length=10),
        ),
    ]
