# Generated by Django 3.1.2 on 2021-04-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_auto_20210410_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='temporary',
            field=models.BooleanField(default=False),
        ),
    ]
