# Generated by Django 3.1.2 on 2021-03-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_auto_20210315_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='year_in_school',
            new_name='privacy',
        ),
    ]
