# Generated by Django 3.1.7 on 2021-03-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['-last_modified', 'pk']},
        ),
        migrations.AlterField(
            model_name='folder',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
