# Generated by Django 3.1.7 on 2021-03-30 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('folder', '0002_auto_20210329_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='present_in_shared_me_of',
            field=models.ManyToManyField(related_name='shared_with_me_folders', to=settings.AUTH_USER_MODEL),
        ),
    ]
