# Generated by Django 3.1.2 on 2021-03-27 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('folder', '0002_auto_20210327_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='shared_among',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shared_folders', to=settings.AUTH_USER_MODEL),
        ),
    ]
