# Generated by Django 3.1.2 on 2021-04-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0003_folder_present_in_shared_me_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
