# Generated by Django 3.1.2 on 2021-03-27 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('folder', '0004_auto_20210327_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='shared_among',
        ),
        migrations.AddField(
            model_name='folder',
            name='shared_among',
            field=models.ManyToManyField(related_name='shared_folders', to=settings.AUTH_USER_MODEL),
        ),
    ]
