# Generated by Django 3.1.2 on 2021-04-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0004_folder_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='temporary',
            field=models.BooleanField(default=False),
        ),
    ]
