# Generated by Django 3.1.2 on 2021-04-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0005_folder_temporary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='temporary',
        ),
    ]
