# Generated by Django 3.1.2 on 2021-03-27 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='root',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='folder.folder'),
        ),
    ]
