# Generated by Django 3.1.2 on 2021-03-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='filesystem',
            field=models.JSONField(default={'root': {'children': {}, 'parent': None, 'type': 'folder'}}),
        ),
    ]
