# Generated by Django 3.1.2 on 2021-03-04 11:40

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210304_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='filesystem',
            field=models.JSONField(default=user.models.filesystem_default_value),
        ),
    ]
