# Generated by Django 3.1.2 on 2021-03-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210304_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='recent',
            field=models.JSONField(default=list),
        ),
    ]
