# Generated by Django 3.1.2 on 2021-03-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210308_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='recent',
            field=models.JSONField(default=dict),
        ),
    ]
