# Generated by Django 3.1.2 on 2021-03-31 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210331_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='capacity',
            new_name='storage_avail',
        ),
        migrations.AddField(
            model_name='profile',
            name='storage_used',
            field=models.IntegerField(default=0),
        ),
    ]
