# Generated by Django 3.1.2 on 2021-04-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210331_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tour_seen',
            field=models.BooleanField(default=False),
        ),
    ]
